services:
  app:
    image: magic-vente-stock
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    secrets:
      - MAGIC_VENTE_STOCK_DB_USERNAME
      - MAGIC_VENTE_STOCK_DB_PASSWORD
    environment:
      SPRING_PROFILES_ACTIVE: dev

secrets:
  MAGIC_VENTE_STOCK_DB_USERNAME:
    file: ./etc/secrets/db_username.txt
  MAGIC_VENTE_STOCK_DB_PASSWORD:
    file: ./etc/secrets/db_password.txt